name: deploy-preview

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - run: pnpm i
      - run: pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: preview-dist
          commit_message: deploy ${{ github.ref }}
          enable_jekyll: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
